### PR TITLE
new user- Contacts feature

### PR DESCRIPTION
**Pull request by ValiTu1**
added contacts  -new user creation

### CODE REVIEW

**Review by melisabeyazrt — APPROVED** [review]
great job

**Review by melisabeyazrt — APPROVED** [review]
great job

**Review by melisabeyazrt — APPROVED** [review]
great job

**Review by hiltas73 — APPROVED** [review]
good job

**Review by hiltas73 — APPROVED** [review]
g

**Review by hiltas73 — APPROVED** [review]
g

**Review by melisabeyazrt — APPROVED** [review]
Great job

**Pull request merged**
